### ISSUE TITLE
Saliency Map for other transformer based models 

### ISSUE THREAD

**Issue by ajay01994** [jalammar/ecco#20] opened 2021-01-09 07:15 UTC
Hi @jalammar 

Thanks for creating this library , I do follow your posts and explanation on transformer models  and you explain i quite well and in simple way . However i was working on  BERT/BART models for various NLP downstream tasks like (sentiment ,intent etc  classifications ) which uses pre-trained  large language  models , I wish to ask you can we  do saliency map visualizations on  this library for custom transformer models , if so can you explain how ?

Looking forward for your reply 

Thanks 

Ajay sahu

**Comment by djstrong** [comment] 2021-01-09 11:25
It is duplicate of #6

**Comment by jalammar** [comment] 2021-01-10 12:23
Hi Ajay,

We intend to do that as @djstrong mentioned. It's not supported yet. In the meantime, you might want to try Captum https://captum.ai/tutorials/Bert_SQUAD_Interpret

**Closed by jalammar** 2021-01-10 12:23 UTC
